# Test override - for isolated test environment
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-deps
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: bash -c 'poetry install --no-root && poetry run python manage.py runserver 0.0.0.0:8000'

  nginx:
    ports:
      - "${HOST_BIND_IP:-127.0.0.1}:${TEST_PORT:-8002}:80"

volumes:
  static-volume:
    driver: local
