version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/app
    command: poetry run python manage.py runserver 0.0.0.0:8000
