services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-deps
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "${HOST_BIND_IP:-127.0.0.1}:${DEV_PORT:-8001}:8000"
    command: bash -c 'poetry install --no-root && poetry run python manage.py runserver 0.0.0.0:8000'

volumes:
  static-volume:
    driver: local
