name: Build Check

on:
  workflow_call:

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env.test from example
        run: cp .env.example .env.test

      - name: Build Docker image
        run: |
          docker compose --progress plain -f docker-compose.yml --env-file .env.test build --no-cache web
