name: Build Check

on:
  workflow_call:

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (production)
        run: |
          cp -f .env.dev .env
          docker compose -f docker-compose.yml build --pull --no-cache --progress=plain web
