name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  format-and-lint:
    uses: ./.github/workflows/format-and-lint.yml

  run-tests:
    uses: ./.github/workflows/run-tests.yml

  build-check:
    needs: [format-and-lint, run-tests]
    uses: ./.github/workflows/build-check.yml
