name: Format and Lint

on:
  workflow_call:

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install Poetry
        run: |
          pip install poetry==1.8.3
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run lint check
        run: make lint-check

      - name: Run format check
        run: make format-check
