name: Run Tests

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-type: [unit-test, e2e-test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install and configure Poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.in-project true

      - name: Create test env file
        run: |
          if [ ! -f .env.test ]; then
              cp .env.example .env.test
          fi

      - name: Install dependencies
        # We install main dependencies as well, because the tests import the app
        run: poetry install --no-root --sync

      - name: Run ${{ matrix.test-type }}
        run: make ${{ matrix.test-type }}
