name: Run Tests

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install and configure Poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.in-project true
          
      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run Django Tests
        env:
          PVT_LLM_API_URL: http://127.0.0.1:8000
          SUMMARY_MAX_CHARS: 600
        run: |
          poetry run pytest